### ISSUE TITLE
How to get the output into a csv file?

### ISSUE THREAD

**Issue by subhasismaji** [watson-developer-cloud/personality-insights-twitter-python#10]
Hi, the code is running absolutely fine. Could you please let me know how to get the output into a CSV file. Thanks.

**Comment by neil-boyette-ibm** [comment]
This sample doesn't have an option for that, however if you look at https://github.com/watson-developer-cloud/personality-insights-twitter-python/blob/master/twitteranalyzer.py#L91 you'll see where it sets the header to json. If you change that to `text/csv` the PI API call will return results in csv. After that it should be straight forward to save the response.
